version: 0.2
env:
  variables:
      ###############################################################
      #           INTEGRATE FORTIFY SCANCENTRAL                     #
        FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN: "new!nectI0n"
        FCLI_DEFAULT_SSC_USER: "seongjun.cho"
        FCLI_DEFAULT_SSC_PASSWORD: "new!nectI0n"
        FCLI_DEFAULT_SSC_CI_TOKEN: "83e025ab-f18a-4f65-8054-f84fc117585f"
        FCLI_DEFAULT_SSC_URL: "http://13.209.176.153:8080/ssc/"
        SSC_APP_VERSION_ID: "3"
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade awscli
  pre_build:
    commands:
      #- mvn clean compile test
      #- mvn clean
      echo "pre_build"
  build:
    commands:
      #- mvn package
      echo "build"
  post_build:
    commands:
      ###################################################
      #             INTEGRATE FORTIFY SAST              #
      #                                                 #
      # For FORTIFY ON DEMAND uncomment the next line   #
      #- bash fortify_sast_fod_template.bash
      #                                                 #
      # For FORTIFY SCANCENTRAL uncomment the next line #
      - bash fortify_sast_scancentral_template.bash
      #                                                 #
      # For LOCAL FORTIFY SCA uncomment the next line   #
      #- bash fortify_sast_local_template.bash
      #                                                 #
      ###################################################

